Repository namoldak/Backend, pull requests merged in 2023-01, with the labels that each got.

#5 [FEAT] Swagger file 추가 #4
  build.gradle
  src/main/java/com/example/namoldak/config/WebSecurityConfig.java
  src/main/java/com/example/namoldak/dto/RequestDto/SignupRequestDto.java
Labels: enhancement

#11 [FEAT] Room 입장하기 API 및 전체 조회 오류 수정 #10
  src/main/java/com/example/namoldak/controller/GameRoomController.java
  src/main/java/com/example/namoldak/domain/GameRoomMember.java
  src/main/java/com/example/namoldak/repository/GameRoomMemberRepository.java
  src/main/java/com/example/namoldak/repository/GameRoomRepository.java
  src/main/java/com/example/namoldak/service/GameRoomService.java
Labels: enhancement

#13 [FEAT] 웹소켓 configuration 추가 #1
  build.gradle
  src/main/java/com/example/namoldak/config/SocketHandler.java
  src/main/java/com/example/namoldak/config/WebSocketConfig.java
Labels: documentation

#17 [FEAT] 공통 응답 포맷 적용
  src/main/java/com/example/namoldak/controller/GameRoomController.java
  src/main/java/com/example/namoldak/controller/MemberController.java
  src/main/java/com/example/namoldak/util/GlobalResponse/CustomException.java
  src/main/java/com/example/namoldak/util/GlobalResponse/ExceptionAdvice.java
  src/main/java/com/example/namoldak/util/GlobalResponse/GlobalResponseDto.java
  src/main/java/com/example/namoldak/util/GlobalResponse/ResponseUtil.java
  src/main/java/com/example/namoldak/util/GlobalResponse/code/ErrorCode.java
  src/main/java/com/example/namoldak/util/GlobalResponse/code/SuccessCode.java
Labels: enhancement

#18 [FEAT] - 게임룸 전체조회 페이징 처리 #15
  src/main/java/com/example/namoldak/controller/GameRoomController.java
  src/main/java/com/example/namoldak/controller/MemberController.java
  src/main/java/com/example/namoldak/repository/GameRoomRepository.java
  src/main/java/com/example/namoldak/service/GameRoomService.java
  src/main/java/com/example/namoldak/service/MemberService.java
Labels: enhancement

#20 [FEAT][REFACTOR] - 전체조회 키워드 검색기능 추가, 에러코드 성공코드 StatusCode로 통일 #19
  src/main/java/com/example/namoldak/controller/GameRoomController.java
  src/main/java/com/example/namoldak/controller/MemberController.java
  src/main/java/com/example/namoldak/dto/ResponseDto/PrivateResponseBody.java
  src/main/java/com/example/namoldak/repository/GameRoomRepository.java
  src/main/java/com/example/namoldak/service/GameRoomService.java
  src/main/java/com/example/namoldak/util/GlobalResponse/CustomException.java
  src/main/java/com/example/namoldak/util/GlobalResponse/ExceptionAdvice.java
  src/main/java/com/example/namoldak/util/GlobalResponse/GlobalResponseDto.java
  src/main/java/com/example/namoldak/util/GlobalResponse/ResponseUtil.java
  src/main/java/com/example/namoldak/util/GlobalResponse/code/StatusCode.java
  src/main/java/com/example/namoldak/util/GlobalResponse/code/SuccessCode.java
Labels: enhancement

#27 [FEAT] 방 나가기 기능에 대한 커밋 #25
  src/main/java/com/example/namoldak/controller/GameRoomController.java
  src/main/java/com/example/namoldak/domain/ChatMessage.java
  src/main/java/com/example/namoldak/domain/GameRoom.java
  src/main/java/com/example/namoldak/repository/GameRoomMemberRepository.java
  src/main/java/com/example/namoldak/service/GameRoomService.java
Labels: enhancement

#34 [FEAT] 정답 건너뛰기 API 구현 (#32)
  src/main/java/com/example/namoldak/controller/GameController.java
  src/main/java/com/example/namoldak/domain/GameMessage.java
  src/main/java/com/example/namoldak/service/GameService.java
Labels: enhancement

#35 [FEAT] 정답 모달 API 구현 (#33)
  src/main/java/com/example/namoldak/controller/GameRearController.java
  src/main/java/com/example/namoldak/domain/GameStartSet.java
  src/main/java/com/example/namoldak/dto/RequestDto/AnswerDto.java
  src/main/java/com/example/namoldak/repository/GameStartSetRepository.java
  src/main/java/com/example/namoldak/service/GameRearService.java
Labels: enhancement

#38 [FEAT] - 게임시작 API 구현 #37
  build.gradle
  src/main/java/com/example/namoldak/controller/GameController.java
  src/main/java/com/example/namoldak/domain/GameMessage.java
  src/main/java/com/example/namoldak/domain/GameRoom.java
  src/main/java/com/example/namoldak/domain/GameRoomMember.java
  src/main/java/com/example/namoldak/repository/GameRoomRepository.java
  src/main/java/com/example/namoldak/repository/GameStartSetRepository.java
  src/main/java/com/example/namoldak/repository/KeywordRepository.java
  src/main/java/com/example/namoldak/service/GameRearService.java
  src/main/java/com/example/namoldak/service/GameRoomService.java
  src/main/java/com/example/namoldak/service/GameService.java
Labels: enhancement

#80 [CHORE] API 주소 및 자잘한 수정 (#79)
  src/main/java/com/example/namoldak/config/RedisConfig.java
  src/main/java/com/example/namoldak/config/WebSecurityConfig.java
  src/main/java/com/example/namoldak/controller/GameController.java
  src/main/java/com/example/namoldak/controller/GameRearController.java
  src/main/java/com/example/namoldak/controller/GameRoomController.java
  src/main/java/com/example/namoldak/controller/MemberController.java
  src/main/java/com/example/namoldak/controller/PostController.java
  src/main/java/com/example/namoldak/domain/ChatMessage.java
  src/main/java/com/example/namoldak/domain/GameRoomAttendee.java
  src/main/java/com/example/namoldak/domain/GameStartSet.java
  src/main/java/com/example/namoldak/dto/RequestDto/AnswerDto.java
  src/main/java/com/example/namoldak/dto/ResponseDto/CommentResponseDto.java
  src/main/java/com/example/namoldak/dto/ResponseDto/PostResponseDto.java
  src/main/java/com/example/namoldak/dto/ResponseDto/VictoryDto.java
  src/main/java/com/example/namoldak/repository/ChatRoomRepository.java
  src/main/java/com/example/namoldak/repository/GameRoomRepository.java
  src/main/java/com/example/namoldak/repository/KeywordRepository.java
  src/main/java/com/example/namoldak/service/ChatRoomService.java
  src/main/java/com/example/namoldak/service/GameRearService.java
  src/main/java/com/example/namoldak/service/GameService.java
  src/main/java/com/example/namoldak/service/PostService.java
  src/main/java/com/example/namoldak/util/security/UserDetailsImpl.java
Labels: documentation

#84 [FEAT] 카테고리별 게시글 조회 API 구현 (#83)
  src/main/java/com/example/namoldak/controller/PostController.java
  src/main/java/com/example/namoldak/dto/ResponseDto/PostResponseDto.java
  src/main/java/com/example/namoldak/dto/ResponseDto/PostResponseListDto.java
  src/main/java/com/example/namoldak/repository/PostRepository.java
  src/main/java/com/example/namoldak/service/PostService.java
Labels: enhancement

#86 [FEAT] 게임방 전체 조회 시 페이지 수 출력 (#85)
  src/main/java/com/example/namoldak/controller/GameRoomController.java
  src/main/java/com/example/namoldak/dto/ResponseDto/GameRoomResponseListDto.java
  src/main/java/com/example/namoldak/dto/ResponseDto/PostResponseListDto.java
  src/main/java/com/example/namoldak/service/GameRoomService.java
Labels: enhancement

#88 [FEAT] 게시글 상세 조회 API (#44)
  src/main/java/com/example/namoldak/controller/PostController.java
  src/main/java/com/example/namoldak/dto/ResponseDto/CommentResponseDto.java
  src/main/java/com/example/namoldak/dto/ResponseDto/PostResponseDto.java
  src/main/java/com/example/namoldak/repository/ChatRoomRepository.java
  src/main/java/com/example/namoldak/repository/CommentRepository.java
  src/main/java/com/example/namoldak/service/ChatRoomService.java
  src/main/java/com/example/namoldak/service/PostService.java
Labels: enhancement

#123 [FIX] 카테고리 랜덤조회 부분 Enum으로 변경 #122
  src/main/java/com/example/namoldak/domain/Category.java
  src/main/java/com/example/namoldak/service/GameService.java
Labels: bug, enhancement

#129 pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#131 build-setup-wrapper (#130)
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement

#137 first test cd (#136)
  .github/workflows/gradle.yml
  appspec.yml
  scripts/deploy.sh
Labels: enhancement

#138 second cd test (#136)
  .github/workflows/gradle.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: bug

#139 third cd test (#136)
  scripts/deploy.sh
Labels: bug

#140 fourth cd test (#136)
  .github/workflows/gradle.yml
  scripts/deploy.sh
Labels: bug

#141 fifth cd test (#136)
  .github/workflows/gradle.yml
  scripts/deploy.sh
Labels: bug

#142 7th cd test (#136)
  .github/workflows/gradle.yml
Labels: bug

#151 [FEAT] 암호화 테스트 #136
  src/main/resources/application.properties
  src/main/resources/application.tar.gpg
Labels: enhancement

#154 Fix/cd
  .github/workflows/gradle.yml
  .gitignore
  src/main/resources/.application.tar.gpg.swp
  src/main/resources/application.properties
  src/main/resources/application.tar.gpg
Labels: bug

#175 S3 이미지 업로드
  build.gradle
  src/main/java/com/example/namoldak/NamoldakApplication.java
  src/main/java/com/example/namoldak/config/AwsS3Config.java
  src/main/java/com/example/namoldak/controller/AwsS3Controller.java
  src/main/java/com/example/namoldak/controller/PostController.java
  src/main/java/com/example/namoldak/domain/Post.java
  src/main/java/com/example/namoldak/dto/ResponseDto/PostResponseDto.java
  src/main/java/com/example/namoldak/service/PostService.java
  src/main/java/com/example/namoldak/util/s3/S3Uploader.java
  src/main/resources/application.properties
  src/main/resources/application.tar.gpg
Labels: enhancement

#178 [FIX] 이미지 null 허용
  src/main/java/com/example/namoldak/domain/Post.java
  src/main/java/com/example/namoldak/service/PostService.java
Labels: bug

#179 [FIX] 이미지 null 허용 #177
  src/main/java/com/example/namoldak/controller/PostController.java
  src/main/java/com/example/namoldak/domain/Post.java
  src/main/java/com/example/namoldak/service/PostService.java
Labels: bug

#181 [FIX] 이미지 null 허용 #177
  src/main/java/com/example/namoldak/service/PostService.java
Labels: bug

#182 [FIX] 이미지 null 허용 #177
  src/main/java/com/example/namoldak/service/PostService.java
  src/main/java/com/example/namoldak/util/s3/S3Uploader.java
Labels: bug

#187 [FIX] CI/CD #124 #136
  .github/workflows/gradle.yml
  appspec.yml
  scripts/deploy.sh
Labels: bug

#190 [REFACTOR] 댓글 반환값 수정 #189
  src/main/java/com/example/namoldak/controller/CommentController.java
  src/main/java/com/example/namoldak/dto/ResponseDto/CommentResponseDto.java
  src/main/java/com/example/namoldak/service/CommentService.java
Labels: enhancement

#193 [REFACTOR] 게시글 작성 시 반환 타입 수정 #192
  src/main/java/com/example/namoldak/service/PostService.java
Labels: enhancement

#203 [REFACTOR] repositoryService로 수정 #202
  src/main/java/com/example/namoldak/service/CommentService.java
Labels: enhancement

#206 [REFACTOR] 게시글 전체 개수 추가 #205
  src/main/java/com/example/namoldak/controller/PostController.java
  src/main/java/com/example/namoldak/domain/Post.java
  src/main/java/com/example/namoldak/dto/ResponseDto/PostResponseListDto.java
  src/main/java/com/example/namoldak/service/PostService.java
Labels: enhancement

#210 [FEAT] 댓글 페이징 처리
  src/main/java/com/example/namoldak/controller/CommentController.java
  src/main/java/com/example/namoldak/controller/PostController.java
  src/main/java/com/example/namoldak/dto/ResponseDto/CommentResponseListDto.java
  src/main/java/com/example/namoldak/repository/CommentRepository.java
  src/main/java/com/example/namoldak/service/CommentService.java
  src/main/java/com/example/namoldak/service/PostService.java
Labels: enhancement

#215 [FEAT] 자유게시판, 마이포스트로 수정
  src/main/java/com/example/namoldak/config/WebSecurityConfig.java
  src/main/java/com/example/namoldak/controller/CommentController.java
  src/main/java/com/example/namoldak/controller/PostController.java
  src/main/java/com/example/namoldak/repository/CommentRepository.java
  src/main/java/com/example/namoldak/repository/PostRepository.java
  src/main/java/com/example/namoldak/service/CommentService.java
  src/main/java/com/example/namoldak/service/PostService.java
  src/main/java/com/example/namoldak/service/RepositoryService.java
Labels: enhancement

#217 [FIX] 회원탈퇴 연관관계 수정 #216
  src/main/java/com/example/namoldak/domain/Member.java
  src/main/java/com/example/namoldak/domain/Post.java
Labels: bug

#221 [FEAT] 게시글 키워드 검색 #220
  src/main/java/com/example/namoldak/controller/PostController.java
  src/main/java/com/example/namoldak/domain/Member.java
  src/main/java/com/example/namoldak/dto/ResponseDto/PostResponseListDto.java
  src/main/java/com/example/namoldak/repository/PostRepository.java
  src/main/java/com/example/namoldak/service/PostService.java
  src/main/java/com/example/namoldak/service/RepositoryService.java
Labels: enhancement

#223 [FIX] 게시글 검색어 기능 수정
  src/main/java/com/example/namoldak/controller/PostController.java
  src/main/java/com/example/namoldak/repository/PostRepository.java
  src/main/java/com/example/namoldak/service/PostService.java
  src/main/java/com/example/namoldak/service/RepositoryService.java
Labels: bug

#224 [FIX] 게시글 검색어 기능 자유게시판만 가능하게 수정 #220
  src/main/java/com/example/namoldak/controller/PostController.java
  src/main/java/com/example/namoldak/repository/PostRepository.java
  src/main/java/com/example/namoldak/service/PostService.java
  src/main/java/com/example/namoldak/service/RepositoryService.java
Labels: enhancement

#234 [FIX] 이미지 업로드 시 도메인 변경
  src/main/java/com/example/namoldak/util/s3/AwsS3Service.java
Labels: enhancement

#235 [REFACTOR] 주석 삭제 #233
  src/main/java/com/example/namoldak/controller/PostController.java
  src/main/java/com/example/namoldak/service/PostService.java
  src/main/java/com/example/namoldak/util/s3/AwsS3Service.java
Labels: duplicate

#238 [FIX] 키워드 검색 예외 처리 #237
  src/main/java/com/example/namoldak/service/PostService.java
  src/main/java/com/example/namoldak/util/GlobalResponse/code/StatusCode.java
Labels: enhancement
